name: wombat

networks:
  internal-network:

volumes:
  kafka-volume:
  postgres-volume:
  jira-volume:

services:

  postgres:
    image: docker.io/library/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS="--auth-host=md5"
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal-network

  flyway-wombatsm:
    image: docker.io/redgate/flyway
    command: migrate info
    volumes:
      - ../db/changelog/:/flyway/sql:ro
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/postgres
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
    networks:
      - internal-network
    depends_on:
      postgres:
        condition: service_healthy

#  jira:
#    image: docker.io/atlassian/jira-core:latest
#    environment:
#      - ATL_DB_TYPE=postgres72
#      - ATL_DB_DRIVER=org.postgresql.Driver
#      - ATL_DB_SCHEMA_NAME=jirasm
#      - ATL_JDBC_USER=postgres
#      - ATL_JDBC_PASSWORD=postgres
#      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
#      - ATL_LICENSE_KEY=AAAB8w0ODAoPeNp9Uk2P2jAQvedXWOoNydmELVKLFKlL4u7SLglKQj+27cEkA3gb7GjssMu/rwnQls9DDvHMvPfmvXmTN0BGfE08n3jdftfv927J/SgnXc9/58wRQC5UXQO6j6IAqYGVwgglAxbnLB2nw4w5cbOcAiaziQbUge85oZKGFybmSwjKmiMKvfjATcW1Fly6hVo64waLBdcQcQPBhot6Per5zo4lX9fQjofJaMTScHj3uC+x11rgup0b3z7sudiIi+oSWQa4AhxGweD+fU6/Tb68pZ+fnh7owPO/Os8CuVujKpvCuJsfqtXMvHAE1+KKFQQGG3A+2cp412XJeQjSHLVkzVQXKOrWn/bljH/nNmslXPa30+nESU4/Jikdp0k0CfNhEtNJxmwhCBGsFSWZrolZANmhECYLVQISu9gzFIb8WBhT/+zf3MyVe2DOTbWdoLCd+OWSSBGpDCmFNiimjQGLLDQxihSNNmppU3Yd67c0ILksjhOxqsKU3eUsooPvG4kXUrli/MlF7dayEU7kb6lepJOxOLAf7XneFmkfCuCp95nh+LdwhfegL8E5l0LzNo4IVlApi0Vy0GZvs9O6b+vHZxzBv0toB3Yuk5lCwuualHs8fSD0/3NqdZ48nBd+5bjYilfNdokZr6zmP7TmY5YwLAIUNq8MbmR8GfaV9ulfLz1K+3g9j1YCFDeq7aYROMQbwMIvHimNt7/bJCCIX02nj
#      - VERBOSE_LOGS=false
#      - JVM_MAXIMUM_MEMORY=2G
#    volumes:
#      - ./jira:/var/atlassian/jira
#    ports:
#      - "8083:8080"
#    healthcheck:
#      test: nc -z localhost 8080 || exit -1
#      start_period: 5s
#      interval: 5s
#      timeout: 3s
#      retries: 30
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - internal-network
