plugins:
  - name: imap_src
    bin: ./build/bin/imap-plugin.so
    conf:
      url: ${WOMBAT_IMAP_ADDRESS:-mail.dev:993}
      username: ${WOMBAT_IMAP_USERNAME:-example@mail.dev}
      password: ${WOMBAT_IMAP_PASSWORD:-password}
      mailbox: ${WOMBAT_IMAP_MAILBOX:-Inbox}
      idleTimeout: ${WOMBAT_IMAP_IDLE_TIMEOUT:-5000}
      verbose: ${WOMBAT_IMAP_VERBOSE:-true}
  - name: tg_dst1
    bin: ./build/bin/telegram-plugin.so
    conf:
      token: ${WOMBAT_TELEGRAM_TOKEN}
  - name: tg_dst2
    bin: ./build/bin/telegram-plugin.so
    conf:
      token: ${WOMBAT_TELEGRAM_TOKEN}
  - name: cel_filter1
    bin: ./build/bin/cel-plugin.so
    conf:
      expr: |
        self.Text.matches(".*some regex.*")
  - name: cel_transform1
    bin: ./build/bin/cel-plugin.so
    conf:
      expr: |
        {"uuid": uuid()}
rules:
  - name: rule1
    src: imap_src
    dst: tg_dst1
    filters:
      - cel_filter1
    transforms:
      - cel_transform1
