bot:
  tag: ${WOMBAT_TAG_PATTERN:-(TEST-\d+)}
cipher:
  key: ${WOMBAT_CIPHER_KEY:-00000100010000100000100010001001}
jira:
  url: ${WOMBAT_JIRA_URL:-localhost}
telegram:
  token: ${WOMBAT_TELEGRAM_TOKEN}
database:
  postgresql:
    url: postgres://${WOMBAT_POSTGRES_USERNAME:-postgres}:${WOMBAT_POSTGRES_PASSWORD:-postgres}@${WOMBAT_POSTGRES_HOST:-localhost}:${WOMBAT_POSTGRES_PORT:-5432}/${WOMBAT_POSTGRES_DATABASE:-postgres}?sslmode=${WOMBAT_POSTGRES_SSLMODE:-disable}

