bot:
  tag: ${TAG_PATTERN:-(KAN-\d+)}
jira:
  url: ${JIRA_URL}
telegram:
  token: ${TELEGRAM_TOKEN}
database:
  postgresql:
    url: postgres://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-postgres}?sslmode=${POSTGRES_SSLMODE:-disable}
kafka:
  group-id: ${KAFKA_GROUP_ID:-wombat}
  bootstrap: ${KAFKA_BOOTSTRAP:-localhost:9092}
  topic: ${KAFKA_TOPIC:-wombat.routing.response}
