bot:
  tag: ${TAG_PATTERN:-(TEST-\d+)}
jira:
  url: ${JIRA_URL:-localhost}
telegram:
  token: ${TELEGRAM_TOKEN}
database:
  postgresql:
    url: postgres://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-postgres}?sslmode=${POSTGRES_SSLMODE:-disable}

