bot:
  tag: ${TAG_PATTERN:-(KAN-\d+)}
jira:
  url: ${JIRA_URL:-https://al-sr.atlassian.net}
  username: ${JIRA_USERNAME:-strtmg@gmail.com}
  token: ${JIRA_TOKEN:-ATATT3xFfGF01GgMt8W_hC6mFoLaON0jxflOe2pmQuHoECSTW9-9AOaNHIYe4VIvqYw6vppAYt77a0GZcxEIk94jFUxv0A5F8VCFWCsL5_nWBnC7jPzfGEg-gLp1R7qh2HMgbLbQfH4AwAKeC_vBnUp9WKB74Rt3RrnnvQOnlC3RH6c1lMzRZ_A=52E87E83}
telegram:
  token: ${TELEGRAM_TOKEN}
database:
  postgresql:
    url: postgres://${POSTGRES_USERNAME:-wombat_rw}:${POSTGRES_PASSWORD:-wombat_rw}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-wombatdb}?sslmode=${POSTGRES_SSLMODE:-disable}
kafka:
  group-id: ${KAFKA_GROUP_ID:-wombat}
  bootstrap: ${KAFKA_BOOTSTRAP:-localhost:9092}
  topic: ${KAFKA_TOPIC:-wombat.routing.response}
