bot:
  tag: (TEST-\\d+)
  emoji: 👍
jira:
  role: TELEGRAM_POSTER
telegram:
  token: ${TELEGRAM_TOKEN}
  webhook: "<your webhook link>"
database:
  postgresql:
    host: ${POSTGRES_HOST:-localhost}
    port: ${POSTGRES_PORT:-5432}
    database: ${POSTGRES_DATABASE:-wombatdb}
    username: ${POSTGRES_USERNAME:-wombat_rw}
    password: ${POSTGRES_PASSWORD:-wombat_rw}
kafka:
  group-id: ${KAFKA_GROUP_ID:-wombat}
  bootstrap: ${KAFKA_BOOTSTRAP:-localhost:9092}
  topic: ${KAFKA_TOPIC:-wombat.response}
