[environments.postgresql]
url = "jdbc:postgresql://postgresql:5432/wombatdb?user=postgres&password=postgres"
user = "wombat_rw"
password = "wombat_rw"
sqlMigrationSuffixes = [".sql"]

[flyway]
environment = "postgresql"
